apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "admissionwebhook.fullname" . }}
  labels:
    app: {{ include "admissionwebhook.name" . }}
    chart: {{ include "admissionwebhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admissionwebhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "admissionwebhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
              - name: webhook-certs
                mountPath: /etc/webhook/certs
                readOnly: true
              - name: config
                mountPath: /etc/config
          ports:
            - name: http
              containerPort: 443
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "admissionwebhook.fullname" . }}-cert
        - name: config
          configMap:
            name: {{ include "admissionwebhook.fullname" . }}-cm
