apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    app.kubernetes.io/name: sleep
    za.co.vodacom/team: testTea
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sleep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sleep
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent